version: "3.8"

networks:
  deall-network:
    name: deall-network

volumes:
  deall-volume:

services:
  mongo:
    container_name: mongo
    image: mongo:5.0
    ports: 
      - 27017:27017
    networks:
      - deall-network
    volumes:
      - deall-volume:/data/db     
  deall-docker:
    container_name: deall-docker
    image: deall-docker:1.0
    ports: 
      - 3000:3000
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - JWT_SECRET=adadech
      - JWT_EXPIRED=1h
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - deall-network

